//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoLocalStorage1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAM
    {
        public string MANL { get; set; }
        public string MASP { get; set; }
        public Nullable<double> SOLUONG { get; set; }
    
        public virtual NGUYENLIEU NGUYENLIEU { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
